### ISSUE TITLE
大佬怎么样可以让这个股票刷新快一点

### ISSUE THREAD

**Issue by EhongLi** [wt365/florus#1]
大佬能把这个股票价格显示刷新速度调快一点吗？

**Comment by wt365** [comment]
可尝试在 `return w;` 前面加入一行代码：
```
widget.refreshAfterDate = new Date(Date.now() + 60000 * 5);
```
按照 *Scriptable* 官方文档解释，上面代码表示5分钟之内不会刷新（但不保证到第5分钟一定马上刷新）。可根据自己需要修改 `*` 后面的数字，注意也不要设置的太频繁。
实际上刷新的频率取决于iOS系统及手机性能，比如在低电量时或者很少滑到有小组件那一屏时，就不会刷新。
也可尝试把小组件放到第一屏。另外，这个显示总会有一定延迟，不建议作为投资决策的依据，想要实时更新的还是建议使用专门的行情app。

**Comment by EhongLi** [comment]
大佬直接在return w 前面一行添加吗，但是我报错：Error on line 107:11: ReferenceError: Can't find variable: widget

**Comment by wt365** [comment]
哦哦，手误，widget改成w。原文我已经改了。

**Comment by EhongLi** [comment]
大佬的小组件是为一个可以显示a股股票的点赞。不知道大佬可不可以出一个简版的 只显示股票 然后多显示一点，最好支持大盘指数
